name: dotnet
on: [pull_request]
jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
    - name: welcome
      run: echo "Hello guys"
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo "Hello guys"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "Hello guys"
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: publish
        run: echo "Hello guys"
      
