name: dotnet
on: [pull_request]
jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
    - name: welcome
      run: echo "Hello guys"
    - name: SonarCloud Scan
      run: echo "Sonar"
  sonar:
    runs-on: ubuntu-latest
    needs: welcome
    steps:
      - name: publish
        run: echo "Hello guys"
      
  build:
    needs: welcome
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo "Hello guys"
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "Hello guys"
  publish:
    runs-on: ubuntu-latest
    needs: sonar
    steps:
      - name: publish
        run: echo "Hello guys"
      
